name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build shared
      working-directory: ./ant_engine
      run: cargo build --verbose
    - name: Run tests shared
      working-directory: ./ant_engine
      run: cargo test --verbose
